# Generated by Django 3.2.9 on 2021-11-20 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.URLField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_description', models.TextField(blank=True, max_length=500)),
                ('company_address', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=200)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
