# Generated by Django 3.2.9 on 2021-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_auto_20211121_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='client_id',
            field=models.CharField(blank=True, default='Tav4IE44R', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, default='m71hKrrcTMUchhNHV9vKm8iml', max_length=200),
        ),
    ]
