# Generated by Django 3.2.9 on 2021-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_auto_20211121_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='client_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
