# Generated by Django 3.2.9 on 2021-11-21 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auths', '0005_auto_20211121_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='company',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='token',
        ),
        migrations.RemoveField(
            model_name='company',
            name='token_expiration',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=250, unique=True)),
                ('token', models.CharField(blank=True, max_length=200)),
                ('redirect_url', models.URLField(blank=True, help_text='Page you want to redirect to')),
                ('domain', models.URLField(blank=True, help_text='Domain on which the app is located')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='apps/')),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.company', verbose_name='company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
