# Generated by Django 3.2.9 on 2021-11-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0007_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_premium',
        ),
        migrations.AddField(
            model_name='application',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
